version: "3.8"
services:
    shared-costs-front:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: shared-costs-front-server
        restart: always
        ports:
            - 4200:80
        volumes: 
            - ./html:/usr/share/nginx/html/
volumes:
    html: {}